<a href="https://colab.research.google.com/github/1Vishal-singh1/ML-Basics/blob/main/ML3_20181CSE0794.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x=np.random.randint(10,size=(1,30))
y=x**2+3*x+1
x=x.reshape(-1,1)
y=y.reshape(-1,1)
x_new=np.split(x,2)
y_new=np.split(y,2)
print(x_new[0])
print(x_new[1])
print(y_new[0])
print(y_new[1])

[[1]
 [7]
 [0]
 [9]
 [2]
 [1]
 [7]
 [5]
 [2]
 [7]
 [8]
 [7]
 [8]
 [0]
 [7]]
[[6]
 [4]
 [3]
 [7]
 [7]
 [0]
 [1]
 [3]
 [8]
 [2]
 [2]
 [3]
 [2]
 [6]
 [6]]
[[  5]
 [ 71]
 [  1]
 [109]
 [ 11]
 [  5]
 [ 71]
 [ 41]
 [ 11]
 [ 71]
 [ 89]
 [ 71]
 [ 89]
 [  1]
 [ 71]]
[[55]
 [29]
 [19]
 [71]
 [71]
 [ 1]
 [ 5]
 [19]
 [89]
 [11]
 [11]
 [19]
 [11]
 [55]
 [55]]


In [ ]:
from sklearn.linear_model import LinearRegression
LRmodel=LinearRegression()
LRmodel.fit(x_new[0], y_new[0])
x_predict=LRmodel.predict(x_new[1])
x_predict=np.rint(x_predict)
from sklearn.metrics import accuracy_score
accuracy_score(y_new[1],x_predict)

0.06666666666666667

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dmodel=DecisionTreeRegressor()
dmodel.fit(x_new[0], y_new[0])
dx_predict=dmodel.predict(x_new[1])
dx_predict=np.rint(dx_predict)
from sklearn.metrics import accuracy_score
accuracy_score(y_new[1],dx_predict)

0.5333333333333333

In [ ]:
from sklearn import tree
x= [[0, 0], [1, 1]]
y= [[0, 1],[0,0]]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(x, y)
clf.predict([[0,1.5],[0,0]])

array([[0, 0],
       [0, 1]])